-- MySQL Script generated by MySQL Workbench
-- 05/13/17 12:04:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`encuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuestas` (
  `id_encuesta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `id_curso` INT(11) NOT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`id_encuesta`));


-- -----------------------------------------------------
-- Table `mydb`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preguntas` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `id_encuesta` INT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  INDEX `fk_preguntas_encuestas_idx` (`id_encuesta` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuestas` (
  `id_respuesta` INT NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_respuesta`),
  INDEX `fk_respuestas_preguntas1_idx` (`id_pregunta` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`tipos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_usuarios` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tipo`));


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_tipos_usuarios1_idx` (`id_tipo` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comisiones` (
  `id_comision` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_comision`));


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `id_comision` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_cursos_comisiones1_idx` (`id_comision` ASC),
  INDEX `fk_cursos_usuarios1_idx` (`id_usuario` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`encuestas_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuestas_has_usuarios` (
  `encuestas_id_encuesta` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`encuestas_id_encuesta`, `usuarios_id_usuario`),
  INDEX `fk_encuestas_has_usuarios_usuarios1_idx` (`usuarios_id_usuario` ASC),
  INDEX `fk_encuestas_has_usuarios_encuestas1_idx` (`encuestas_id_encuesta` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
